app:
    resource: "@AppBundle/Controller/"
    type:     annotation


projects:
    pattern:  /projects
    defaults: { _controller: AppBundle:Default:projects }
    requirements:
        _method:  ANY

project:
    pattern:  /project/{id}
    defaults: { _controller: AppBundle:Default:project }
    requirements:
        _method:  GET
