app:
    resource: "@AppBundle/Controller/"
    type:     annotation


projects:
    pattern:  /projects
    defaults: { _controller: AppBundle:Default:projects }
    requirements:
        _method:  ANY

project:
    pattern:  /project/{projectID}
    defaults: { _controller: AppBundle:Default:project }
    requirements:
        _method:  GET


client:
    pattern:  /client/{clientID}
    defaults: { _controller: AppBundle:Default:client }
    requirements:
        _method:  GET
