app:
    resource: "@AppBundle/Controller/"
    type:     annotation


projects:
    pattern:  /projects
    defaults: { _controller: AppBundle:Projects:projects }
    requirements:
        _method:  GET

project:
    pattern:  /project/{projectID}
    defaults: { _controller: AppBundle:Projects:project }
    requirements:
        _method:  GET

project-overview:
    pattern:  /project-overview
    defaults: { _controller: AppBundle:Projects:projectOverview }
    requirements:
        _method:  GET


client:
    pattern:  /client/{clientID}
    defaults: { _controller: AppBundle:Default:client }
    requirements:
        _method:  GET

login:
    pattern:  /login
    defaults: { _controller: AppBundle:Default:login }
    requirements:
        _method:  GET


error404:
    path: /404
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    TwigBundle:Exception:error404.html.twig

