app:
    resource: "@AppBundle/Controller/"
    type:     annotation


contact:
    pattern:  /contact
    defaults: { _controller: AppBundle:Default:contact }
    requirements:
        _method:  GET
