# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html


parameters:
    entity.user_entity: "AppBundle:User"
    entity.project_entity: "AppBundle:Project"
    entity.section_entity: "AppBundle:Section"
    entity.task_entity: "AppBundle:Task"

services:
    doc:
        class: AppBundle\Controller\DefaultController
        arguments: ["@doctrine.orm.entity_manager"]

    user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - %entity.user_entity%

    project_repository:
        class: AppBundle\Repository\ProjectRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - %entity.project_entity%

    section_repository:
        class: AppBundle\Repository\SectionRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - %entity.section_entity%

    task_repository:
        class: AppBundle\Repository\TaskRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - %entity.task_entity%

