<?php

namespace AppBundle\Entity;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllProjects()
	{
		$em 		= $this->getEntityManager();
		$query 		= $em->createQuery('SELECT p FROM AppBundle:Project p');
		$projects 	= $query->getResult();

		return $projects;
	}

	public function getProjectById($projectID)
	{
		$em 		= $this->getEntityManager();
		$query 		= $em->createQuery('SELECT p FROM AppBundle:Project p WHERE p.id = :id')->setParameter('id', $projectID);
		$project 	= $query->getResult();

		return $project;
	}

}
