<?php

namespace AppBundle\Entity;

/**
 * sectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSectionsByProjectID($projectID)
	{
		$em 		= $this->getEntityManager();
		$query 		= $em->createQuery('SELECT s FROM AppBundle:Section s WHERE s.projectId = :project_id')->setParameter('project_id', $projectID);
		$sections 	= $query->getResult();

		return $sections;
	}
}
