<?php

namespace AppBundle\Entity;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTasksByProjectIDAndSectionID($projectID)
	{
		$em 		= $this->getEntityManager();
		$query 		= $em->createQuery('SELECT t FROM AppBundle:Task t WHERE t.projectID = :projectID')->setParameter('projectID', $projectID);
		$tasks 		= $query->getResult();

		return $tasks;
	}
}
